builders:
  cinch_gen:
    import: "package:cinch_gen/cinch_gen.dart"
    builder_factories: ["cinch"]
    build_extensions: {".dart": [".cinch.dart"]}
    auto_apply: root_package
    build_to: source