name: cinch_gen
description: cinch is powerful http client for dart, support native and js, http client using dio.
version: 6.2.0
repository: https://github.com/tatsuyuki25/cinch
resolution: workspace

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  # 不使用`0.38.3`，有BUG
  analyzer: ">=6.9.0 <8.0.0"
  build: ^3.0.0
  cinch: ^6.0.1
  path: ">=1.8.0 <2.0.0"
  source_gen: ^3.0.0
  dio: ^5.8.0+1

dev_dependencies:
  source_gen_test: ^1.3.0
  test: ^1.26.3
