# Name of this workspace, this is used for display purpose on the CLI
# and on your IDEs.
name: cinch
repository: https://github.com/tatsuyuki25/cinch

# Array of globs to search for packages.
# Instead of one recursive glob, we use multiple globs to avoid
# searching every single directory in the repo.
packages:
  - packages/*
  - packages/*/*
  - packages/*/*/*

command:
  version:
    # Generate commit links in package changelogs.
    linkToCommits: false
    # Skip generation of shared changelogs file in the repo root
    workspaceChangelog: true
