name: cinch
description: http request library
version: 1.0.1
author: tatsuyuki <tatsuyuki@program.com.tw>
homepage: https://www.program.com.tw

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  analyzer: ^0.33.0
  build: ^1.1.0
  path: ^1.6.2
  source_gen: "^0.9.4"
  dio: ^2.0.14

dev_dependencies:
  build_test: ^0.10.0
  test: ^1.3.0