name: cinch
description: http request library
version: 1.1.1
author: tatsuyuki <tatsuyuki@program.com.tw>
homepage: https://gitlab.program.com.tw/FlutterGroup/cinch
publish_to: http://172.16.65.36:8080

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  analyzer: ^0.36.3
  build: ^1.1.4
  path: ^1.6.2
  source_gen: ^0.9.4+2
  dio: ^2.1.7

dev_dependencies:
  build_test: ^0.10.8
  test: ^1.6.4
  build_runner: ^1.5.2