name: cinch
description: http request library
version: 1.1.4
author: tatsuyuki <tatsuyuki@program.com.tw>
homepage: https://gitlab.program.com.tw/FlutterGroup/cinch
publish_to: http://10.0.0.55:8083

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  analyzer: ^0.36.3
  build: ^1.1.4
  path: ^1.6.2
  source_gen: ^0.9.4+2
  dio: ^2.1.7

dev_dependencies:
  source_gen_test: ^0.1.0+3
  test: ^1.6.4
  build_runner: ^1.6.1