name: cinch
description: http request library
version: 1.3.2
homepage: https://gitlab.program.com.tw/FlutterGroup/cinch
publish_to: http://10.0.0.55:8083

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  # 不使用`0.38.3`，有BUG
  analyzer: ">=0.38.4 <=0.39.2+1"
  build: ^1.2.2
  path: ^1.6.4
  source_gen: ^0.9.4+6
  dio: ^3.0.7

dev_dependencies:
  source_gen_test: ^0.1.0+6
  test: ^1.9.4
  build_runner: ^1.7.2