name: cinch
description: http request library
version: 1.3.6
homepage: https://gitlab.program.com.tw/FlutterGroup/cinch
publish_to: http://pub.program.com.tw:8080

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  # 不使用`0.38.3`，有BUG
  analyzer: ">=0.38.4 <1.0.0"
  build: ">=1.2.2 <2.0.0"
  path: ">=1.6.4 <2.0.0"
  source_gen: ">=0.9.4+6 <1.0.0"
  dio: ^3.0.9

dev_dependencies:
  source_gen_test: ^0.1.1
  test: ^1.15.3
  build_runner: ^1.10.0