name: cinch
description: cinch is powerful http client for dart, support native and js, http client using dio.
version: 5.0.3
repository: https://github.com/tatsuyuki25/cinch

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dio: ^5.8.0+1
  meta: ^1.16.0

dev_dependencies:
  build_runner: ^2.4.10
  test: ^1.25.5