name: cinch
description: cinch is powerful http client for dart, support native and js, http client using dio.
version: 6.0.1
repository: https://github.com/tatsuyuki25/cinch
resolution: workspace

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  dio: ^5.8.0+1

dev_dependencies:
  build_runner: ^2.5.4
  test: ^1.26.2