name: cinch
description: cinch is powerful http client for dart, support native and js, http client using dio.
version: 2.0.0-nullsafety.1
repository: https://github.com/tatsuyuki25/cinch

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dio: ^4.0.0-beta7

dev_dependencies:
  test: ^1.16.8
  build_runner: ^1.12.1