name: cinch
description: cinch is powerful http client for dart, support native and js, http client using dio.
version: 2.1.0
repository: https://github.com/tatsuyuki25/cinch

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dio: ^4.0.1

dev_dependencies:
  build_runner: ^2.1.4
  test: ^1.19.2