name: cinch
description: cinch is powerful http client for dart, support native and js, http client using dio.
version: 3.0.0-dev.2
repository: https://github.com/tatsuyuki25/cinch

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dio: ^5.0.0
  meta: ^1.8.0

dev_dependencies:
  build_runner: ^2.3.0
  test: ^1.21.6