name: cinch
description: cinch is powerful http client for dart, support native and js, http client using dio.
version: 2.0.0-nullsafety.2
repository: https://github.com/tatsuyuki25/cinch

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dio: ^4.0.0

dev_dependencies:
  build_runner: ^2.0.3
  test: ^1.16.8