name: cinch
description: cinch is powerful http client for dart, support native and js, http client using dio.
version: 4.0.0
repository: https://github.com/tatsuyuki25/cinch

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dio: ^5.2.1+1
  meta: ^1.9.1

dev_dependencies:
  build_runner: ^2.4.5
  test: ^1.24.3