name: cinch_gen
description: cinch is powerful http client for dart, support native and js, http client using dio.
version: 4.1.1
repository: https://github.com/tatsuyuki25/cinch

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  # 不使用`0.38.3`，有BUG
  analyzer: ">=5.0.0 <7.0.0"
  build: ^2.4.1
  cinch: ^4.1.1
  path: ">=1.8.0 <2.0.0"
  source_gen: "^1.5.0"
  dio: ^5.4.3

dev_dependencies:
  source_gen_test: ^1.0.6
  test: ^1.25.5
